### ISSUE TITLE
[Errata]: AI Demo error

### ISSUE THREAD

**Issue by lisenjie757** [kendryte/k510_docs#103]
I meet this error, how to solve it.
./object_detect_demo: error while loading shared libraries: libopencv_core.so.4.5: cannot open shared object file: No such file or directory

**Comment by MrThanlon** [comment]
Please checkout `/usr/lib/libopencv_core.so*`.
If not, make sure that `BR2_PACKAGE_OPENCV4=y` is appear in the `/path/to/k510_buildroot/k510_crb_lp3_v1_2_defconfig/.config`.

**Comment by chenhb3** [comment]
If there is no feedback on the results or situation for more than 7 days, the issue will be closed.If you have any questions later, please create it again, thank you!
