### ISSUE TITLE
[Improvement]: 

### ISSUE THREAD

**Issue by mark4th** [kendryte/k510_docs#48]
### Improvement

there is absolutely NO documentation in this documentation that I can see.

I see a bunch of chinese garbage for SDK and your SDK is 100% useless to me.

Where is the documentation for the register map
where is the documentation for the interrupt controller
where is the documentation for every single peripheral device
where is the documentation for the DMA
where is the documentation for the SPI bus?
where is the documentation for the UARTS?

and i mean for the DEVICES not the freeking SDK api calls that are of no use to me at all.

You people never document your hardware, that makes the hardware PURE GARBAGE.

**Comment by wuwentao** [comment]
@mark4th Thank you very much for your suggestion,  we are working on english version docs,  and will publish it later once review and approved
