### ISSUE TITLE
[other]: input/output gpio pin map

### ISSUE THREAD

**Issue by StanislavIr** [kendryte/k510_docs#77]
### Other

Hello. Where to find pinout information for chip k510?   Need information about what pins could be set as gpio.

**Comment by chenhb3** [comment]
Please refer to:https://github.com/kendryte/k510_docs/releases/download/v1.8/K510_CRB_SCH_MECH_FILE.zip

**Comment by chenhb3** [comment]
If there is no feedback on the results or situation for more than 7 days, the issue will be closed.If you have any questions later, please create it again, thank you!
