### ISSUE TITLE
[Improvement]: 

### ISSUE THREAD

**Issue by Murphy41** [kendryte/k510_docs#99]
### Improvement

you might need to run this line before get pycrypto:
```
sudo apt-get install python-dev
```

**Comment by wuwentao** [comment]
thank you very much for your issue .
we are using `python3`, not` python2` , so it don't required `python-dev`.
our dockerfile source code can works and don't show any error: `https://github.com/kendryte/k510_buildroot/blob/dev/tools/docker/Dockerfile_20.04_ok`

please check and confirm.
I will close this issue now, if there is any error exist, you can reopen this issue and report again.
